MODEL:
  #NAME: mobilenet_standard_conv_224
  NAME: 'mobilenet_dw_224'
  IMAGE_SIZE: [224, 224, 3]
  NUM_CLASSES: 1000
  ALPHA: 1.0
  
TRAIN:
  MAX_EPOCHS: 200
  BATCH_SIZE: 64
  WORKERS: 2
  PRINT_FREQ: 10
  OPTIMIZER:
    OPTIMIZER: 'SGD'
    LEARNING_RATE: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
  REPRODUCIBILITY:
    REPRODUCIBILITY: True
    SEED: 0

TEST:
  BATCH_SIZE: 64

DATASET:
  TRAIN: '/home/feaf-seat-1/Documents/nesvera/datapool/dataset/train'
  VALID: '/home/feaf-seat-1/Documents/nesvera/datapool/dataset/val'

EXP_DIR: './experiments/'
LOG_DIR: './experiments/'
RESUME_CHECKPOINT: ''
