MODEL:
  #NAME: mobilenet_standard_conv_224
  NAME: 'mobilenet_dw_224'
  IMAGE_SIZE: [224, 224, 3]
  NUM_CLASSES: 1000
  ALPHA: 1.0
  
TRAIN:
  MAX_EPOCHS: 200
  BATCH_SIZE: 32
  WORKERS: 4
  PRINT_FREQ: 2000
  OPTIMIZER:
    OPTIMIZER: 'SGD'
    LEARNING_RATE: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
  REPRODUCIBILITY:
    REPRODUCIBILITY: True
    SEED: 0

TEST:
  BATCH_SIZE: 48

DATASET:
  TRAIN: '/home/nesvera/Documents/neural_nets/classification/classifiers/dataset/GTSRB/train'
  VALID: ''

EXP_DIR: './experiments/'
LOG_DIR: './experiments/'
RESUME_CHECKPOINT: ''
